#

- name: download zentao
  get_url:
    url: "{{download_url}}"
    dest: "{{download_dir}}"
    force: no

- name: rpm install zentao
  shell:  "tar -zxvf  {{download_dir}}/{{file_name}} -C /opt"

- name: start zentao
  shell: /opt/zbox/zbox start
  register: finished

  # TODO 配置文件
